import type { Metadata } from "next";
import "@styles/global.scss";
import classnames from "classnames/bind";
import $ from "./layout.module.scss";
import { isMobile } from "react-device-detect";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cn = classnames.bind($);

  return (
    <html lang="ko">
      <body>
        <div className={cn({ [$.isMobile]: !isMobile })}>{children}</div>
      </body>
    </html>
  );
}
